// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StockInfosColumns holds the columns for the "stock_infos" table.
	StockInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// StockInfosTable holds the schema information for the "stock_infos" table.
	StockInfosTable = &schema.Table{
		Name:       "stock_infos",
		Columns:    StockInfosColumns,
		PrimaryKey: []*schema.Column{StockInfosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StockInfosTable,
	}
)

func init() {
}
