# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error_reason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pykit.errors import errors_pb2 as pykit_dot_errors_dot_errors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65rror_reason.proto\x12\x10go_app.hellworld\x1a\x19pykit/errors/errors.proto*H\n\x0b\x45rrorReason\x12\x19\n\x0fSTOCK_NOT_FOUND\x10\x00\x1a\x04\xa8\x45\x94\x03\x12\x18\n\x0eNODE_NOT_FOUND\x10\x01\x1a\x04\xa8\x45\xf4\x03\x1a\x04\xa0\x45\xf4\x03\x42\x42\n\x10go_app.hellworldP\x01Z\x1ago_app/hellworld;hellworld\xa2\x02\x0f\x41PIHelloworldV1b\x06proto3')

_ERRORREASON = DESCRIPTOR.enum_types_by_name['ErrorReason']
ErrorReason = enum_type_wrapper.EnumTypeWrapper(_ERRORREASON)
STOCK_NOT_FOUND = 0
NODE_NOT_FOUND = 1


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020go_app.hellworldP\001Z\032go_app/hellworld;hellworld\242\002\017APIHelloworldV1'
  _ERRORREASON._options = None
  _ERRORREASON._serialized_options = b'\240E\364\003'
  _ERRORREASON.values_by_name["STOCK_NOT_FOUND"]._options = None
  _ERRORREASON.values_by_name["STOCK_NOT_FOUND"]._serialized_options = b'\250E\224\003'
  _ERRORREASON.values_by_name["NODE_NOT_FOUND"]._options = None
  _ERRORREASON.values_by_name["NODE_NOT_FOUND"]._serialized_options = b'\250E\364\003'
  _ERRORREASON._serialized_start=67
  _ERRORREASON._serialized_end=139
# @@protoc_insertion_point(module_scope)
