// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gostock/internal/biz"
	"gostock/internal/conf"
	"gostock/internal/data"
	"gostock/internal/server"
	"gostock/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	redisClient := data.NewRedisClient(confData, logger)
	dataData, cleanup, err := data.NewData(client, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	incomeRepo := data.NewIncomeRepo(dataData, logger)
	incomeUsecase := biz.NewIncomeUsecase(incomeRepo, logger)
	incomeService := service.NewIncomeService(incomeUsecase)
	stockInfoRepo := data.NewStockInfoRepo(dataData, logger)
	stockInfoUsecase := biz.NewStockInfoUsecase(stockInfoRepo, logger)
	stockService := service.NewStockInfoService(stockInfoUsecase)
	httpServer := server.NewHTTPServer(confServer, greeterService, incomeService, stockService, logger)
	grpcServer := server.NewGRPCServer(confServer, greeterService, incomeService, stockService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
