# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errors/errors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='errors/errors.proto',
  package='errors',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x65rrors/errors.proto\x12\x06\x65rrors\x1a google/protobuf/descriptor.proto\"\x98\x01\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12.\n\x08metadata\x18\x04 \x03(\x0b\x32\x1c.errors.Status.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:3\n\x0c\x64\x65\x66\x61ult_code\x12\x1c.google.protobuf.EnumOptions\x18\xd4\x08 \x01(\x05:0\n\x04\x63ode\x12!.google.protobuf.EnumValueOptions\x18\xd5\x08 \x01(\x05\x42Y\n\x18\x63om.github.kratos.errorsP\x01Z,github.com/go-kratos/kratos/v2/errors;errors\xa2\x02\x0cKratosErrorsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


DEFAULT_CODE_FIELD_NUMBER = 1108
default_code = _descriptor.FieldDescriptor(
  name='default_code', full_name='errors.default_code', index=0,
  number=1108, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)
CODE_FIELD_NUMBER = 1109
code = _descriptor.FieldDescriptor(
  name='code', full_name='errors.code', index=1,
  number=1109, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)


_STATUS_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='errors.Status.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='errors.Status.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='errors.Status.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=218,
)

_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='errors.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='errors.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='errors.Status.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='errors.Status.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='errors.Status.metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STATUS_METADATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=218,
)

_STATUS_METADATAENTRY.containing_type = _STATUS
_STATUS.fields_by_name['metadata'].message_type = _STATUS_METADATAENTRY
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.extensions_by_name['default_code'] = default_code
DESCRIPTOR.extensions_by_name['code'] = code
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _STATUS_METADATAENTRY,
    __module__ = 'errors.errors_pb2'
    # @@protoc_insertion_point(class_scope:errors.Status.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _STATUS,
  __module__ = 'errors.errors_pb2'
  # @@protoc_insertion_point(class_scope:errors.Status)
  ))
_sym_db.RegisterMessage(Status)
_sym_db.RegisterMessage(Status.MetadataEntry)

google_dot_protobuf_dot_descriptor__pb2.EnumOptions.RegisterExtension(default_code)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(code)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.github.kratos.errorsP\001Z,github.com/go-kratos/kratos/v2/errors;errors\242\002\014KratosErrors'))
_STATUS_METADATAENTRY.has_options = True
_STATUS_METADATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
