// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"gostock/internal/data/ent/stockinfo"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// StockInfo is the model entity for the StockInfo schema.
type StockInfo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockInfo) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockinfo.FieldID:
			values[i] = new(sql.NullInt64)
		case stockinfo.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type StockInfo", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockInfo fields.
func (si *StockInfo) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockinfo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			si.ID = int(value.Int64)
		case stockinfo.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				si.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this StockInfo.
// Note that you need to call StockInfo.Unwrap() before calling this method if this StockInfo
// was returned from a transaction, and the transaction was committed or rolled back.
func (si *StockInfo) Update() *StockInfoUpdateOne {
	return (&StockInfoClient{config: si.config}).UpdateOne(si)
}

// Unwrap unwraps the StockInfo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (si *StockInfo) Unwrap() *StockInfo {
	tx, ok := si.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockInfo is not a transactional entity")
	}
	si.config.driver = tx.drv
	return si
}

// String implements the fmt.Stringer.
func (si *StockInfo) String() string {
	var builder strings.Builder
	builder.WriteString("StockInfo(")
	builder.WriteString(fmt.Sprintf("id=%v", si.ID))
	builder.WriteString(", name=")
	builder.WriteString(si.Name)
	builder.WriteByte(')')
	return builder.String()
}

// StockInfos is a parsable slice of StockInfo.
type StockInfos []*StockInfo

func (si StockInfos) config(cfg config) {
	for _i := range si {
		si[_i].config = cfg
	}
}
