// Code generated by entc, DO NOT EDIT.

package ent

import (
	"gostock/internal/data/ent/schema"
	"gostock/internal/data/ent/stockinfo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	stockinfoFields := schema.StockInfo{}.Fields()
	_ = stockinfoFields
	// stockinfoDescIsLeader is the schema descriptor for is_leader field.
	stockinfoDescIsLeader := stockinfoFields[15].Descriptor()
	// stockinfo.DefaultIsLeader holds the default value on creation for the is_leader field.
	stockinfo.DefaultIsLeader = stockinfoDescIsLeader.Default.(bool)
}
