# Code generated by protoc-gen-go-errors. DO NOT EDIT.


from pykit import errors
from api.crawler.v1 import error_reason_pb2

# This is a compile-time assertion to ensure that this generated file
# is compatible with the kratos package it is being compiled against.
_ = errors.SupportPackageIsVersion1


def is_stock_not_found(err: Exception) -> bool:
    if not err:
        return False
    e = errors.from_error(err)
    reason = error_reason_pb2.ErrorReason.Name(error_reason_pb2.STOCK_NOT_FOUND)
    return e.reason == reason and e.code == 404


def error_stock_not_found(msg: str) -> errors.Error:
    reason = error_reason_pb2.ErrorReason.Name(error_reason_pb2.STOCK_NOT_FOUND)
    return errors.Error(code=400, reason=reason, message=msg)
