# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.crawler.v1 import index_pb2 as api_dot_crawler_dot_v1_dot_index__pb2
from api.crawler.v1 import stock_info_pb2 as api_dot_crawler_dot_v1_dot_stock__info__pb2


class StockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockInfo = channel.unary_unary(
                '/api.crawler.v1.StockService/GetStockInfo',
                request_serializer=api_dot_crawler_dot_v1_dot_stock__info__pb2.StockBasicRequest.SerializeToString,
                response_deserializer=api_dot_crawler_dot_v1_dot_stock__info__pb2.StockBasic.FromString,
                )
        self.GetIndexInfo = channel.unary_unary(
                '/api.crawler.v1.StockService/GetIndexInfo',
                request_serializer=api_dot_crawler_dot_v1_dot_index__pb2.IndexRequest.SerializeToString,
                response_deserializer=api_dot_crawler_dot_v1_dot_index__pb2.Index.FromString,
                )


class StockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStockInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockInfo,
                    request_deserializer=api_dot_crawler_dot_v1_dot_stock__info__pb2.StockBasicRequest.FromString,
                    response_serializer=api_dot_crawler_dot_v1_dot_stock__info__pb2.StockBasic.SerializeToString,
            ),
            'GetIndexInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexInfo,
                    request_deserializer=api_dot_crawler_dot_v1_dot_index__pb2.IndexRequest.FromString,
                    response_serializer=api_dot_crawler_dot_v1_dot_index__pb2.Index.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.crawler.v1.StockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStockInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.crawler.v1.StockService/GetStockInfo',
            api_dot_crawler_dot_v1_dot_stock__info__pb2.StockBasicRequest.SerializeToString,
            api_dot_crawler_dot_v1_dot_stock__info__pb2.StockBasic.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.crawler.v1.StockService/GetIndexInfo',
            api_dot_crawler_dot_v1_dot_index__pb2.IndexRequest.SerializeToString,
            api_dot_crawler_dot_v1_dot_index__pb2.Index.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
