# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/stock/v1/index.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pi/stock/v1/index.proto\x12\x0c\x61pi.stock.v1\"\x0e\n\x0cIndexRequest\"\x8a\x02\n\x05Index\x12\x0f\n\x07ts_code\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x61rea\x18\x04 \x01(\t\x12\x10\n\x08industry\x18\x05 \x01(\t\x12\x10\n\x08\x66ullname\x18\x06 \x01(\t\x12\x0e\n\x06\x65nname\x18\x07 \x01(\t\x12\x0f\n\x07\x63nspell\x18\x08 \x01(\t\x12\x0e\n\x06market\x18\t \x01(\t\x12\x10\n\x08\x65xchange\x18\n \x01(\t\x12\x11\n\tcurr_type\x18\x0b \x01(\t\x12\x13\n\x0blist_status\x18\x0c \x01(\t\x12\x11\n\tlist_date\x18\r \x01(\t\x12\x13\n\x0b\x64\x65list_date\x18\x0e \x01(\t\x12\r\n\x05is_hs\x18\x0f \x01(\tB)\n\x0c\x61pi.stock.v1P\x01Z\x17gostock/api/stock/v1;v1b\x06proto3')



_INDEXREQUEST = DESCRIPTOR.message_types_by_name['IndexRequest']
_INDEX = DESCRIPTOR.message_types_by_name['Index']
IndexRequest = _reflection.GeneratedProtocolMessageType('IndexRequest', (_message.Message,), {
  'DESCRIPTOR' : _INDEXREQUEST,
  '__module__' : 'api.stock.v1.index_pb2'
  # @@protoc_insertion_point(class_scope:api.stock.v1.IndexRequest)
  })
_sym_db.RegisterMessage(IndexRequest)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'api.stock.v1.index_pb2'
  # @@protoc_insertion_point(class_scope:api.stock.v1.Index)
  })
_sym_db.RegisterMessage(Index)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014api.stock.v1P\001Z\027gostock/api/stock/v1;v1'
  _INDEXREQUEST._serialized_start=42
  _INDEXREQUEST._serialized_end=56
  _INDEX._serialized_start=59
  _INDEX._serialized_end=325
# @@protoc_insertion_point(module_scope)
