# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pykit/errors/errors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pykit/errors/errors.proto\x12\x06\x65rrors\x1a google/protobuf/descriptor.proto\"\x98\x01\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12.\n\x08metadata\x18\x04 \x03(\x0b\x32\x1c.errors.Status.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:3\n\x0c\x64\x65\x66\x61ult_code\x12\x1c.google.protobuf.EnumOptions\x18\xd4\x08 \x01(\x05:0\n\x04\x63ode\x12!.google.protobuf.EnumValueOptions\x18\xd5\x08 \x01(\x05\x42Y\n\x18\x63om.github.kratos.errorsP\x01Z,github.com/go-kratos/kratos/v2/errors;errors\xa2\x02\x0cKratosErrorsb\x06proto3')


DEFAULT_CODE_FIELD_NUMBER = 1108
default_code = DESCRIPTOR.extensions_by_name['default_code']
CODE_FIELD_NUMBER = 1109
code = DESCRIPTOR.extensions_by_name['code']

_STATUS = DESCRIPTOR.message_types_by_name['Status']
_STATUS_METADATAENTRY = _STATUS.nested_types_by_name['MetadataEntry']
Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATUS_METADATAENTRY,
    '__module__' : 'pykit.errors.errors_pb2'
    # @@protoc_insertion_point(class_scope:errors.Status.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'pykit.errors.errors_pb2'
  # @@protoc_insertion_point(class_scope:errors.Status)
  })
_sym_db.RegisterMessage(Status)
_sym_db.RegisterMessage(Status.MetadataEntry)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.EnumOptions.RegisterExtension(default_code)
  google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(code)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.github.kratos.errorsP\001Z,github.com/go-kratos/kratos/v2/errors;errors\242\002\014KratosErrors'
  _STATUS_METADATAENTRY._options = None
  _STATUS_METADATAENTRY._serialized_options = b'8\001'
  _STATUS._serialized_start=72
  _STATUS._serialized_end=224
  _STATUS_METADATAENTRY._serialized_start=177
  _STATUS_METADATAENTRY._serialized_end=224
# @@protoc_insertion_point(module_scope)
