// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.5.0
// source: evaluate/v1/income.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateIncomeRequest) Reset() {
	*x = CreateIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncomeRequest) ProtoMessage() {}

func (x *CreateIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncomeRequest.ProtoReflect.Descriptor instead.
func (*CreateIncomeRequest) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{0}
}

type CreateIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateIncomeReply) Reset() {
	*x = CreateIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncomeReply) ProtoMessage() {}

func (x *CreateIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncomeReply.ProtoReflect.Descriptor instead.
func (*CreateIncomeReply) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{1}
}

type UpdateIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateIncomeRequest) Reset() {
	*x = UpdateIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncomeRequest) ProtoMessage() {}

func (x *UpdateIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncomeRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncomeRequest) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{2}
}

type UpdateIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateIncomeReply) Reset() {
	*x = UpdateIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncomeReply) ProtoMessage() {}

func (x *UpdateIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncomeReply.ProtoReflect.Descriptor instead.
func (*UpdateIncomeReply) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{3}
}

type DeleteIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIncomeRequest) Reset() {
	*x = DeleteIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIncomeRequest) ProtoMessage() {}

func (x *DeleteIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIncomeRequest.ProtoReflect.Descriptor instead.
func (*DeleteIncomeRequest) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{4}
}

type DeleteIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIncomeReply) Reset() {
	*x = DeleteIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIncomeReply) ProtoMessage() {}

func (x *DeleteIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIncomeReply.ProtoReflect.Descriptor instead.
func (*DeleteIncomeReply) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{5}
}

type GetIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockId int32 `protobuf:"varint,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
}

func (x *GetIncomeRequest) Reset() {
	*x = GetIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeRequest) ProtoMessage() {}

func (x *GetIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeRequest.ProtoReflect.Descriptor instead.
func (*GetIncomeRequest) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{6}
}

func (x *GetIncomeRequest) GetStockId() int32 {
	if x != nil {
		return x.StockId
	}
	return 0
}

type GetIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockId int32 `protobuf:"varint,1,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
}

func (x *GetIncomeReply) Reset() {
	*x = GetIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncomeReply) ProtoMessage() {}

func (x *GetIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncomeReply.ProtoReflect.Descriptor instead.
func (*GetIncomeReply) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{7}
}

func (x *GetIncomeReply) GetStockId() int32 {
	if x != nil {
		return x.StockId
	}
	return 0
}

type ListIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListIncomeRequest) Reset() {
	*x = ListIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncomeRequest) ProtoMessage() {}

func (x *ListIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncomeRequest.ProtoReflect.Descriptor instead.
func (*ListIncomeRequest) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{8}
}

type ListIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListIncomeReply) Reset() {
	*x = ListIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_v1_income_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncomeReply) ProtoMessage() {}

func (x *ListIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_v1_income_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncomeReply.ProtoReflect.Descriptor instead.
func (*ListIncomeReply) Descriptor() ([]byte, []int) {
	return file_evaluate_v1_income_proto_rawDescGZIP(), []int{9}
}

var File_evaluate_v1_income_proto protoreflect.FileDescriptor

var file_evaluate_v1_income_proto_rawDesc = []byte{
	0x0a, 0x18, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e,
	0x63, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xb1, 0x03,
	0x0a, 0x06, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x50, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x65, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x65,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x65,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x65,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1d, 0x2e, 0x65, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x65, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12,
	0x14, 0x2f, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2f, 0x7b, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x4a, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x1e, 0x2e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x2f, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x67, 0x6f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_evaluate_v1_income_proto_rawDescOnce sync.Once
	file_evaluate_v1_income_proto_rawDescData = file_evaluate_v1_income_proto_rawDesc
)

func file_evaluate_v1_income_proto_rawDescGZIP() []byte {
	file_evaluate_v1_income_proto_rawDescOnce.Do(func() {
		file_evaluate_v1_income_proto_rawDescData = protoimpl.X.CompressGZIP(file_evaluate_v1_income_proto_rawDescData)
	})
	return file_evaluate_v1_income_proto_rawDescData
}

var file_evaluate_v1_income_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_evaluate_v1_income_proto_goTypes = []interface{}{
	(*CreateIncomeRequest)(nil), // 0: evaluate.v1.CreateIncomeRequest
	(*CreateIncomeReply)(nil),   // 1: evaluate.v1.CreateIncomeReply
	(*UpdateIncomeRequest)(nil), // 2: evaluate.v1.UpdateIncomeRequest
	(*UpdateIncomeReply)(nil),   // 3: evaluate.v1.UpdateIncomeReply
	(*DeleteIncomeRequest)(nil), // 4: evaluate.v1.DeleteIncomeRequest
	(*DeleteIncomeReply)(nil),   // 5: evaluate.v1.DeleteIncomeReply
	(*GetIncomeRequest)(nil),    // 6: evaluate.v1.GetIncomeRequest
	(*GetIncomeReply)(nil),      // 7: evaluate.v1.GetIncomeReply
	(*ListIncomeRequest)(nil),   // 8: evaluate.v1.ListIncomeRequest
	(*ListIncomeReply)(nil),     // 9: evaluate.v1.ListIncomeReply
}
var file_evaluate_v1_income_proto_depIdxs = []int32{
	0, // 0: evaluate.v1.Income.CreateIncome:input_type -> evaluate.v1.CreateIncomeRequest
	2, // 1: evaluate.v1.Income.UpdateIncome:input_type -> evaluate.v1.UpdateIncomeRequest
	4, // 2: evaluate.v1.Income.DeleteIncome:input_type -> evaluate.v1.DeleteIncomeRequest
	6, // 3: evaluate.v1.Income.GetIncome:input_type -> evaluate.v1.GetIncomeRequest
	8, // 4: evaluate.v1.Income.ListIncome:input_type -> evaluate.v1.ListIncomeRequest
	1, // 5: evaluate.v1.Income.CreateIncome:output_type -> evaluate.v1.CreateIncomeReply
	3, // 6: evaluate.v1.Income.UpdateIncome:output_type -> evaluate.v1.UpdateIncomeReply
	5, // 7: evaluate.v1.Income.DeleteIncome:output_type -> evaluate.v1.DeleteIncomeReply
	7, // 8: evaluate.v1.Income.GetIncome:output_type -> evaluate.v1.GetIncomeReply
	9, // 9: evaluate.v1.Income.ListIncome:output_type -> evaluate.v1.ListIncomeReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evaluate_v1_income_proto_init() }
func file_evaluate_v1_income_proto_init() {
	if File_evaluate_v1_income_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_evaluate_v1_income_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_v1_income_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_evaluate_v1_income_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evaluate_v1_income_proto_goTypes,
		DependencyIndexes: file_evaluate_v1_income_proto_depIdxs,
		MessageInfos:      file_evaluate_v1_income_proto_msgTypes,
	}.Build()
	File_evaluate_v1_income_proto = out.File
	file_evaluate_v1_income_proto_rawDesc = nil
	file_evaluate_v1_income_proto_goTypes = nil
	file_evaluate_v1_income_proto_depIdxs = nil
}
