// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type StockServiceHTTPServer interface {
	GetStockInfo(context.Context, *GetStockInfoRequest) (*StockInfo, error)
}

func RegisterStockServiceHTTPServer(s *http.Server, srv StockServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/stock/{id}", _StockService_GetStockInfo0_HTTP_Handler(srv))
}

func _StockService_GetStockInfo0_HTTP_Handler(srv StockServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStockInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.stock.v1.StockService/GetStockInfo")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStockInfo(ctx, req.(*GetStockInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StockInfo)
		return ctx.Result(200, reply)
	}
}

type StockServiceHTTPClient interface {
	GetStockInfo(ctx context.Context, req *GetStockInfoRequest, opts ...http.CallOption) (rsp *StockInfo, err error)
}

type StockServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStockServiceHTTPClient(client *http.Client) StockServiceHTTPClient {
	return &StockServiceHTTPClientImpl{client}
}

func (c *StockServiceHTTPClientImpl) GetStockInfo(ctx context.Context, in *GetStockInfoRequest, opts ...http.CallOption) (*StockInfo, error) {
	var out StockInfo
	pattern := "/stock/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.stock.v1.StockService/GetStockInfo"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
