// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: stock/v1/stock_info.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockInfoServiceClient is the client API for StockInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockInfoServiceClient interface {
	GetStockInfo(ctx context.Context, in *GetStockInfoRequest, opts ...grpc.CallOption) (*StockInfo, error)
}

type stockInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockInfoServiceClient(cc grpc.ClientConnInterface) StockInfoServiceClient {
	return &stockInfoServiceClient{cc}
}

func (c *stockInfoServiceClient) GetStockInfo(ctx context.Context, in *GetStockInfoRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/api.stock.v1.StockInfoService/GetStockInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockInfoServiceServer is the server API for StockInfoService service.
// All implementations must embed UnimplementedStockInfoServiceServer
// for forward compatibility
type StockInfoServiceServer interface {
	GetStockInfo(context.Context, *GetStockInfoRequest) (*StockInfo, error)
	mustEmbedUnimplementedStockInfoServiceServer()
}

// UnimplementedStockInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStockInfoServiceServer struct {
}

func (UnimplementedStockInfoServiceServer) GetStockInfo(context.Context, *GetStockInfoRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockInfo not implemented")
}
func (UnimplementedStockInfoServiceServer) mustEmbedUnimplementedStockInfoServiceServer() {}

// UnsafeStockInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockInfoServiceServer will
// result in compilation errors.
type UnsafeStockInfoServiceServer interface {
	mustEmbedUnimplementedStockInfoServiceServer()
}

func RegisterStockInfoServiceServer(s grpc.ServiceRegistrar, srv StockInfoServiceServer) {
	s.RegisterService(&StockInfoService_ServiceDesc, srv)
}

func _StockInfoService_GetStockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockInfoServiceServer).GetStockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.stock.v1.StockInfoService/GetStockInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockInfoServiceServer).GetStockInfo(ctx, req.(*GetStockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockInfoService_ServiceDesc is the grpc.ServiceDesc for StockInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.stock.v1.StockInfoService",
	HandlerType: (*StockInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockInfo",
			Handler:    _StockInfoService_GetStockInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/v1/stock_info.proto",
}
