# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler/internal/config/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crawler.internal.config import crawler_pb2 as crawler_dot_internal_dot_config_dot_crawler__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$crawler/internal/config/config.proto\x12\x0e\x63rawler.config\x1a%crawler/internal/config/crawler.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8d\x01\n\tBootstrap\x12&\n\x06server\x18\x01 \x01(\x0b\x32\x16.crawler.config.Server\x12.\n\nconnection\x18\x02 \x01(\x0b\x32\x1a.crawler.config.Connection\x12(\n\x07\x63rawler\x18\x03 \x01(\x0b\x32\x17.crawler.config.Crawler\"\x84\x02\n\x06Server\x12)\n\x04http\x18\x01 \x01(\x0b\x32\x1b.crawler.config.Server.HTTP\x12)\n\x04grpc\x18\x02 \x01(\x0b\x32\x1b.crawler.config.Server.GRPC\x1aQ\n\x04HTTP\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12*\n\x07timeout\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x1aQ\n\x04GRPC\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12*\n\x07timeout\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\"\xd4\x03\n\nConnection\x12\x35\n\x08\x64\x61tabase\x18\x01 \x01(\x0b\x32#.crawler.config.Connection.Database\x12/\n\x05redis\x18\x02 \x01(\x0b\x32 .crawler.config.Connection.Redis\x12\x31\n\x06\x63onsul\x18\x03 \x01(\x0b\x32!.crawler.config.Connection.Consul\x1a*\n\x08\x44\x61tabase\x12\x0e\n\x06\x64river\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x1a\xd8\x01\n\x05Redis\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\n\n\x02\x64\x62\x18\x04 \x01(\x05\x12/\n\x0cread_timeout\x18\x05 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x30\n\rwrite_timeout\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\x12/\n\x0c\x64ial_timeout\x18\x07 \x01(\x0b\x32\x19.google.protobuf.Duration\x1a$\n\x06\x43onsul\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x62\x06proto3')



_BOOTSTRAP = DESCRIPTOR.message_types_by_name['Bootstrap']
_SERVER = DESCRIPTOR.message_types_by_name['Server']
_SERVER_HTTP = _SERVER.nested_types_by_name['HTTP']
_SERVER_GRPC = _SERVER.nested_types_by_name['GRPC']
_CONNECTION = DESCRIPTOR.message_types_by_name['Connection']
_CONNECTION_DATABASE = _CONNECTION.nested_types_by_name['Database']
_CONNECTION_REDIS = _CONNECTION.nested_types_by_name['Redis']
_CONNECTION_CONSUL = _CONNECTION.nested_types_by_name['Consul']
Bootstrap = _reflection.GeneratedProtocolMessageType('Bootstrap', (_message.Message,), {
  'DESCRIPTOR' : _BOOTSTRAP,
  '__module__' : 'crawler.internal.config.config_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Bootstrap)
  })
_sym_db.RegisterMessage(Bootstrap)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), {

  'HTTP' : _reflection.GeneratedProtocolMessageType('HTTP', (_message.Message,), {
    'DESCRIPTOR' : _SERVER_HTTP,
    '__module__' : 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Server.HTTP)
    })
  ,

  'GRPC' : _reflection.GeneratedProtocolMessageType('GRPC', (_message.Message,), {
    'DESCRIPTOR' : _SERVER_GRPC,
    '__module__' : 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Server.GRPC)
    })
  ,
  'DESCRIPTOR' : _SERVER,
  '__module__' : 'crawler.internal.config.config_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Server)
  })
_sym_db.RegisterMessage(Server)
_sym_db.RegisterMessage(Server.HTTP)
_sym_db.RegisterMessage(Server.GRPC)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), {

  'Database' : _reflection.GeneratedProtocolMessageType('Database', (_message.Message,), {
    'DESCRIPTOR' : _CONNECTION_DATABASE,
    '__module__' : 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Connection.Database)
    })
  ,

  'Redis' : _reflection.GeneratedProtocolMessageType('Redis', (_message.Message,), {
    'DESCRIPTOR' : _CONNECTION_REDIS,
    '__module__' : 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Connection.Redis)
    })
  ,

  'Consul' : _reflection.GeneratedProtocolMessageType('Consul', (_message.Message,), {
    'DESCRIPTOR' : _CONNECTION_CONSUL,
    '__module__' : 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Connection.Consul)
    })
  ,
  'DESCRIPTOR' : _CONNECTION,
  '__module__' : 'crawler.internal.config.config_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Connection)
  })
_sym_db.RegisterMessage(Connection)
_sym_db.RegisterMessage(Connection.Database)
_sym_db.RegisterMessage(Connection.Redis)
_sym_db.RegisterMessage(Connection.Consul)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOTSTRAP._serialized_start=128
  _BOOTSTRAP._serialized_end=269
  _SERVER._serialized_start=272
  _SERVER._serialized_end=532
  _SERVER_HTTP._serialized_start=368
  _SERVER_HTTP._serialized_end=449
  _SERVER_GRPC._serialized_start=451
  _SERVER_GRPC._serialized_end=532
  _CONNECTION._serialized_start=535
  _CONNECTION._serialized_end=1003
  _CONNECTION_DATABASE._serialized_start=704
  _CONNECTION_DATABASE._serialized_end=746
  _CONNECTION_REDIS._serialized_start=749
  _CONNECTION_REDIS._serialized_end=965
  _CONNECTION_CONSUL._serialized_start=967
  _CONNECTION_CONSUL._serialized_end=1003
# @@protoc_insertion_point(module_scope)
