# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler/internal/config/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crawler.internal.config import crawler_pb2 as crawler_dot_internal_dot_config_dot_crawler__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='crawler/internal/config/config.proto',
  package='crawler.config',
  syntax='proto3',
  serialized_pb=_b('\n$crawler/internal/config/config.proto\x12\x0e\x63rawler.config\x1a%crawler/internal/config/crawler.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8d\x01\n\tBootstrap\x12&\n\x06server\x18\x01 \x01(\x0b\x32\x16.crawler.config.Server\x12.\n\nconnection\x18\x02 \x01(\x0b\x32\x1a.crawler.config.Connection\x12(\n\x07\x63rawler\x18\x03 \x01(\x0b\x32\x17.crawler.config.Crawler\"\x84\x02\n\x06Server\x12)\n\x04http\x18\x01 \x01(\x0b\x32\x1b.crawler.config.Server.HTTP\x12)\n\x04grpc\x18\x02 \x01(\x0b\x32\x1b.crawler.config.Server.GRPC\x1aQ\n\x04HTTP\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12*\n\x07timeout\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x1aQ\n\x04GRPC\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12*\n\x07timeout\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\"\xfb\x02\n\nConnection\x12\x35\n\x08\x64\x61tabase\x18\x01 \x01(\x0b\x32#.crawler.config.Connection.Database\x12/\n\x05redis\x18\x02 \x01(\x0b\x32 .crawler.config.Connection.Redis\x1a*\n\x08\x44\x61tabase\x12\x0e\n\x06\x64river\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x1a\xd8\x01\n\x05Redis\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\n\n\x02\x64\x62\x18\x04 \x01(\x05\x12/\n\x0cread_timeout\x18\x05 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x30\n\rwrite_timeout\x18\x06 \x01(\x0b\x32\x19.google.protobuf.Duration\x12/\n\x0c\x64ial_timeout\x18\x07 \x01(\x0b\x32\x19.google.protobuf.Durationb\x06proto3')
  ,
  dependencies=[crawler_dot_internal_dot_config_dot_crawler__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_BOOTSTRAP = _descriptor.Descriptor(
  name='Bootstrap',
  full_name='crawler.config.Bootstrap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='crawler.config.Bootstrap.server', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection', full_name='crawler.config.Bootstrap.connection', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crawler', full_name='crawler.config.Bootstrap.crawler', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=269,
)


_SERVER_HTTP = _descriptor.Descriptor(
  name='HTTP',
  full_name='crawler.config.Server.HTTP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='crawler.config.Server.HTTP.network', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='crawler.config.Server.HTTP.addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='crawler.config.Server.HTTP.timeout', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=449,
)

_SERVER_GRPC = _descriptor.Descriptor(
  name='GRPC',
  full_name='crawler.config.Server.GRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='crawler.config.Server.GRPC.network', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='crawler.config.Server.GRPC.addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='crawler.config.Server.GRPC.timeout', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=532,
)

_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='crawler.config.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='http', full_name='crawler.config.Server.http', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grpc', full_name='crawler.config.Server.grpc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERVER_HTTP, _SERVER_GRPC, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=532,
)


_CONNECTION_DATABASE = _descriptor.Descriptor(
  name='Database',
  full_name='crawler.config.Connection.Database',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='driver', full_name='crawler.config.Connection.Database.driver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='crawler.config.Connection.Database.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=695,
)

_CONNECTION_REDIS = _descriptor.Descriptor(
  name='Redis',
  full_name='crawler.config.Connection.Redis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='crawler.config.Connection.Redis.network', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='crawler.config.Connection.Redis.addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='crawler.config.Connection.Redis.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='db', full_name='crawler.config.Connection.Redis.db', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_timeout', full_name='crawler.config.Connection.Redis.read_timeout', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_timeout', full_name='crawler.config.Connection.Redis.write_timeout', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dial_timeout', full_name='crawler.config.Connection.Redis.dial_timeout', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=914,
)

_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='crawler.config.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='crawler.config.Connection.database', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redis', full_name='crawler.config.Connection.redis', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONNECTION_DATABASE, _CONNECTION_REDIS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=914,
)

_BOOTSTRAP.fields_by_name['server'].message_type = _SERVER
_BOOTSTRAP.fields_by_name['connection'].message_type = _CONNECTION
_BOOTSTRAP.fields_by_name['crawler'].message_type = crawler_dot_internal_dot_config_dot_crawler__pb2._CRAWLER
_SERVER_HTTP.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_SERVER_HTTP.containing_type = _SERVER
_SERVER_GRPC.fields_by_name['timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_SERVER_GRPC.containing_type = _SERVER
_SERVER.fields_by_name['http'].message_type = _SERVER_HTTP
_SERVER.fields_by_name['grpc'].message_type = _SERVER_GRPC
_CONNECTION_DATABASE.containing_type = _CONNECTION
_CONNECTION_REDIS.fields_by_name['read_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CONNECTION_REDIS.fields_by_name['write_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CONNECTION_REDIS.fields_by_name['dial_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CONNECTION_REDIS.containing_type = _CONNECTION
_CONNECTION.fields_by_name['database'].message_type = _CONNECTION_DATABASE
_CONNECTION.fields_by_name['redis'].message_type = _CONNECTION_REDIS
DESCRIPTOR.message_types_by_name['Bootstrap'] = _BOOTSTRAP
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bootstrap = _reflection.GeneratedProtocolMessageType('Bootstrap', (_message.Message,), dict(
  DESCRIPTOR = _BOOTSTRAP,
  __module__ = 'crawler.internal.config.config_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Bootstrap)
  ))
_sym_db.RegisterMessage(Bootstrap)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), dict(

  HTTP = _reflection.GeneratedProtocolMessageType('HTTP', (_message.Message,), dict(
    DESCRIPTOR = _SERVER_HTTP,
    __module__ = 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Server.HTTP)
    ))
  ,

  GRPC = _reflection.GeneratedProtocolMessageType('GRPC', (_message.Message,), dict(
    DESCRIPTOR = _SERVER_GRPC,
    __module__ = 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Server.GRPC)
    ))
  ,
  DESCRIPTOR = _SERVER,
  __module__ = 'crawler.internal.config.config_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Server)
  ))
_sym_db.RegisterMessage(Server)
_sym_db.RegisterMessage(Server.HTTP)
_sym_db.RegisterMessage(Server.GRPC)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(

  Database = _reflection.GeneratedProtocolMessageType('Database', (_message.Message,), dict(
    DESCRIPTOR = _CONNECTION_DATABASE,
    __module__ = 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Connection.Database)
    ))
  ,

  Redis = _reflection.GeneratedProtocolMessageType('Redis', (_message.Message,), dict(
    DESCRIPTOR = _CONNECTION_REDIS,
    __module__ = 'crawler.internal.config.config_pb2'
    # @@protoc_insertion_point(class_scope:crawler.config.Connection.Redis)
    ))
  ,
  DESCRIPTOR = _CONNECTION,
  __module__ = 'crawler.internal.config.config_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Connection)
  ))
_sym_db.RegisterMessage(Connection)
_sym_db.RegisterMessage(Connection.Database)
_sym_db.RegisterMessage(Connection.Redis)


# @@protoc_insertion_point(module_scope)
