# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler/internal/config/crawler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crawler/internal/config/crawler.proto',
  package='crawler.config',
  syntax='proto3',
  serialized_pb=_b('\n%crawler/internal/config/crawler.proto\x12\x0e\x63rawler.config\"C\n\x07\x43rawler\x12\x0e\n\x06\x64river\x18\x01 \x01(\t\x12(\n\x07tushare\x18\x02 \x01(\x0b\x32\x17.crawler.config.Tushare\"\x18\n\x07Tushare\x12\r\n\x05token\x18\x01 \x01(\tb\x06proto3')
)




_CRAWLER = _descriptor.Descriptor(
  name='Crawler',
  full_name='crawler.config.Crawler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='driver', full_name='crawler.config.Crawler.driver', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tushare', full_name='crawler.config.Crawler.tushare', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=124,
)


_TUSHARE = _descriptor.Descriptor(
  name='Tushare',
  full_name='crawler.config.Tushare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='crawler.config.Tushare.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=150,
)

_CRAWLER.fields_by_name['tushare'].message_type = _TUSHARE
DESCRIPTOR.message_types_by_name['Crawler'] = _CRAWLER
DESCRIPTOR.message_types_by_name['Tushare'] = _TUSHARE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Crawler = _reflection.GeneratedProtocolMessageType('Crawler', (_message.Message,), dict(
  DESCRIPTOR = _CRAWLER,
  __module__ = 'crawler.internal.config.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Crawler)
  ))
_sym_db.RegisterMessage(Crawler)

Tushare = _reflection.GeneratedProtocolMessageType('Tushare', (_message.Message,), dict(
  DESCRIPTOR = _TUSHARE,
  __module__ = 'crawler.internal.config.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Tushare)
  ))
_sym_db.RegisterMessage(Tushare)


# @@protoc_insertion_point(module_scope)
