# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crawler/internal/config/crawler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%crawler/internal/config/crawler.proto\x12\x0e\x63rawler.config\"C\n\x07\x43rawler\x12\x0e\n\x06\x64river\x18\x01 \x01(\t\x12(\n\x07tushare\x18\x02 \x01(\x0b\x32\x17.crawler.config.Tushare\"\x18\n\x07Tushare\x12\r\n\x05token\x18\x01 \x01(\tb\x06proto3')



_CRAWLER = DESCRIPTOR.message_types_by_name['Crawler']
_TUSHARE = DESCRIPTOR.message_types_by_name['Tushare']
Crawler = _reflection.GeneratedProtocolMessageType('Crawler', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLER,
  '__module__' : 'crawler.internal.config.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Crawler)
  })
_sym_db.RegisterMessage(Crawler)

Tushare = _reflection.GeneratedProtocolMessageType('Tushare', (_message.Message,), {
  'DESCRIPTOR' : _TUSHARE,
  '__module__' : 'crawler.internal.config.crawler_pb2'
  # @@protoc_insertion_point(class_scope:crawler.config.Tushare)
  })
_sym_db.RegisterMessage(Tushare)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRAWLER._serialized_start=57
  _CRAWLER._serialized_end=124
  _TUSHARE._serialized_start=126
  _TUSHARE._serialized_end=150
# @@protoc_insertion_point(module_scope)
