rsyslog:
  image: vimagick/rsyslog
  container_name: rsyslog
  ports:
    - "514:514/tcp"
    - "514:514/udp"
  volumes:
    - ./rsyslog.conf:/etc/rsyslogd.conf
    - ./data:/var/log
  restart: always
